networks:
  default: mainnet-fork

autofetch_sources: True

dependencies:
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.1
  - Uniswap/v3-core@1.0.0

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.8.12
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.1"
      - "@uniswap=Uniswap/v3-core@1.0.0"
