/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { INFTMINT, INFTMINTInterface } from "../INFTMINT";

const _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
            },
        ],
        name: "burn",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "tokenId",
                type: "uint256",
            },
        ],
        name: "creatorOf",
        outputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "getBaseURL",
        outputs: [
            {
                internalType: "string",
                name: "",
                type: "string",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "string",
                name: "url",
                type: "string",
            },
        ],
        name: "setBaseURL",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];

export class INFTMINT__factory {
    static readonly abi = _abi;
    static createInterface(): INFTMINTInterface {
        return new utils.Interface(_abi) as INFTMINTInterface;
    }
    static connect(
        address: string,
        signerOrProvider: Signer | Provider
    ): INFTMINT {
        return new Contract(address, _abi, signerOrProvider) as INFTMINT;
    }
}
