/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IStrategy, IStrategyInterface } from "../IStrategy";

const _abi = [
    {
        inputs: [
            {
                internalType: "string",
                name: "_function",
                type: "string",
            },
            {
                internalType: "string",
                name: "_values",
                type: "string",
            },
        ],
        name: "getJson",
        outputs: [
            {
                internalType: "string",
                name: "",
                type: "string",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "string",
                name: "_function",
                type: "string",
            },
            {
                internalType: "string",
                name: "_values",
                type: "string",
            },
        ],
        name: "sendJson",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];

export class IStrategy__factory {
    static readonly abi = _abi;
    static createInterface(): IStrategyInterface {
        return new utils.Interface(_abi) as IStrategyInterface;
    }
    static connect(
        address: string,
        signerOrProvider: Signer | Provider
    ): IStrategy {
        return new Contract(address, _abi, signerOrProvider) as IStrategy;
    }
}
