/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Strategy, StrategyInterface } from "../Strategy";

const _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "previousOwner",
                type: "address",
            },
        ],
        name: "OwnershipRenounced",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "previousOwner",
                type: "address",
            },
            {
                indexed: true,
                internalType: "address",
                name: "newOwner",
                type: "address",
            },
        ],
        name: "OwnershipTransferred",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "newOwner",
                type: "address",
            },
        ],
        name: "changeOwner",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "string",
                name: "_function",
                type: "string",
            },
            {
                internalType: "string",
                name: "_values",
                type: "string",
            },
        ],
        name: "getJson",
        outputs: [
            {
                internalType: "string",
                name: "",
                type: "string",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "owner",
        outputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "renounceOwnership",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "string",
                name: "_function",
                type: "string",
            },
            {
                internalType: "string",
                name: "_values",
                type: "string",
            },
        ],
        name: "sendJson",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];

export class Strategy__factory {
    static readonly abi = _abi;
    static createInterface(): StrategyInterface {
        return new utils.Interface(_abi) as StrategyInterface;
    }
    static connect(
        address: string,
        signerOrProvider: Signer | Provider
    ): Strategy {
        return new Contract(address, _abi, signerOrProvider) as Strategy;
    }
}
