/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
    ethers,
    EventFilter,
    Signer,
    BigNumber,
    BigNumberish,
    PopulatedTransaction,
    BaseContract,
    ContractTransaction,
    Overrides,
    CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
    TypedEventFilter,
    TypedEvent,
    TypedListener,
    OnEvent,
} from "./common";

export interface IBeaconInterface extends ethers.utils.Interface {
    functions: {
        "childImplementation()": FunctionFragment;
        "upgradeChildTo(address)": FunctionFragment;
    };

    encodeFunctionData(
        functionFragment: "childImplementation",
        values?: undefined
    ): string;
    encodeFunctionData(
        functionFragment: "upgradeChildTo",
        values: [string]
    ): string;

    decodeFunctionResult(
        functionFragment: "childImplementation",
        data: BytesLike
    ): Result;
    decodeFunctionResult(
        functionFragment: "upgradeChildTo",
        data: BytesLike
    ): Result;

    events: {};
}

export interface IBeacon extends BaseContract {
    connect(signerOrProvider: Signer | Provider | string): this;
    attach(addressOrName: string): this;
    deployed(): Promise<this>;

    interface: IBeaconInterface;

    queryFilter<TEvent extends TypedEvent>(
        event: TypedEventFilter<TEvent>,
        fromBlockOrBlockhash?: string | number | undefined,
        toBlock?: string | number | undefined
    ): Promise<Array<TEvent>>;

    listeners<TEvent extends TypedEvent>(
        eventFilter?: TypedEventFilter<TEvent>
    ): Array<TypedListener<TEvent>>;
    listeners(eventName?: string): Array<Listener>;
    removeAllListeners<TEvent extends TypedEvent>(
        eventFilter: TypedEventFilter<TEvent>
    ): this;
    removeAllListeners(eventName?: string): this;
    off: OnEvent<this>;
    on: OnEvent<this>;
    once: OnEvent<this>;
    removeListener: OnEvent<this>;

    functions: {
        childImplementation(overrides?: CallOverrides): Promise<[string]>;

        upgradeChildTo(
            newImplementation: string,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<ContractTransaction>;
    };

    childImplementation(overrides?: CallOverrides): Promise<string>;

    upgradeChildTo(
        newImplementation: string,
        overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    callStatic: {
        childImplementation(overrides?: CallOverrides): Promise<string>;

        upgradeChildTo(
            newImplementation: string,
            overrides?: CallOverrides
        ): Promise<void>;
    };

    filters: {};

    estimateGas: {
        childImplementation(overrides?: CallOverrides): Promise<BigNumber>;

        upgradeChildTo(
            newImplementation: string,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<BigNumber>;
    };

    populateTransaction: {
        childImplementation(
            overrides?: CallOverrides
        ): Promise<PopulatedTransaction>;

        upgradeChildTo(
            newImplementation: string,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<PopulatedTransaction>;
    };
}
