/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
    ethers,
    EventFilter,
    Signer,
    BigNumber,
    BigNumberish,
    PopulatedTransaction,
    BaseContract,
    ContractTransaction,
    Overrides,
    CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
    TypedEventFilter,
    TypedEvent,
    TypedListener,
    OnEvent,
} from "./common";

export interface IERCMINTInterface extends ethers.utils.Interface {
    functions: {
        "burn(uint256)": FunctionFragment;
        "isEnoughOn(address,uint256)": FunctionFragment;
        "mint(address,uint256)": FunctionFragment;
        "safeDeposit(address,address,uint256)": FunctionFragment;
        "safeWithdraw(address,address,uint256)": FunctionFragment;
        "xburn(address,uint256)": FunctionFragment;
    };

    encodeFunctionData(
        functionFragment: "burn",
        values: [BigNumberish]
    ): string;
    encodeFunctionData(
        functionFragment: "isEnoughOn",
        values: [string, BigNumberish]
    ): string;
    encodeFunctionData(
        functionFragment: "mint",
        values: [string, BigNumberish]
    ): string;
    encodeFunctionData(
        functionFragment: "safeDeposit",
        values: [string, string, BigNumberish]
    ): string;
    encodeFunctionData(
        functionFragment: "safeWithdraw",
        values: [string, string, BigNumberish]
    ): string;
    encodeFunctionData(
        functionFragment: "xburn",
        values: [string, BigNumberish]
    ): string;

    decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
    decodeFunctionResult(
        functionFragment: "isEnoughOn",
        data: BytesLike
    ): Result;
    decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
    decodeFunctionResult(
        functionFragment: "safeDeposit",
        data: BytesLike
    ): Result;
    decodeFunctionResult(
        functionFragment: "safeWithdraw",
        data: BytesLike
    ): Result;
    decodeFunctionResult(functionFragment: "xburn", data: BytesLike): Result;

    events: {};
}

export interface IERCMINT extends BaseContract {
    connect(signerOrProvider: Signer | Provider | string): this;
    attach(addressOrName: string): this;
    deployed(): Promise<this>;

    interface: IERCMINTInterface;

    queryFilter<TEvent extends TypedEvent>(
        event: TypedEventFilter<TEvent>,
        fromBlockOrBlockhash?: string | number | undefined,
        toBlock?: string | number | undefined
    ): Promise<Array<TEvent>>;

    listeners<TEvent extends TypedEvent>(
        eventFilter?: TypedEventFilter<TEvent>
    ): Array<TypedListener<TEvent>>;
    listeners(eventName?: string): Array<Listener>;
    removeAllListeners<TEvent extends TypedEvent>(
        eventFilter: TypedEventFilter<TEvent>
    ): this;
    removeAllListeners(eventName?: string): this;
    off: OnEvent<this>;
    on: OnEvent<this>;
    once: OnEvent<this>;
    removeListener: OnEvent<this>;

    functions: {
        burn(
            amount: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<ContractTransaction>;

        isEnoughOn(
            account: string,
            amount: BigNumberish,
            overrides?: CallOverrides
        ): Promise<[boolean]>;

        mint(
            to: string,
            amount: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<ContractTransaction>;

        safeDeposit(
            from: string,
            to: string,
            amount: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<ContractTransaction>;

        safeWithdraw(
            from: string,
            to: string,
            amount: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<ContractTransaction>;

        xburn(
            from: string,
            amount: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<ContractTransaction>;
    };

    burn(
        amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isEnoughOn(
        account: string,
        amount: BigNumberish,
        overrides?: CallOverrides
    ): Promise<boolean>;

    mint(
        to: string,
        amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    safeDeposit(
        from: string,
        to: string,
        amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    safeWithdraw(
        from: string,
        to: string,
        amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    xburn(
        from: string,
        amount: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    callStatic: {
        burn(amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

        isEnoughOn(
            account: string,
            amount: BigNumberish,
            overrides?: CallOverrides
        ): Promise<boolean>;

        mint(
            to: string,
            amount: BigNumberish,
            overrides?: CallOverrides
        ): Promise<void>;

        safeDeposit(
            from: string,
            to: string,
            amount: BigNumberish,
            overrides?: CallOverrides
        ): Promise<void>;

        safeWithdraw(
            from: string,
            to: string,
            amount: BigNumberish,
            overrides?: CallOverrides
        ): Promise<void>;

        xburn(
            from: string,
            amount: BigNumberish,
            overrides?: CallOverrides
        ): Promise<void>;
    };

    filters: {};

    estimateGas: {
        burn(
            amount: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<BigNumber>;

        isEnoughOn(
            account: string,
            amount: BigNumberish,
            overrides?: CallOverrides
        ): Promise<BigNumber>;

        mint(
            to: string,
            amount: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<BigNumber>;

        safeDeposit(
            from: string,
            to: string,
            amount: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<BigNumber>;

        safeWithdraw(
            from: string,
            to: string,
            amount: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<BigNumber>;

        xburn(
            from: string,
            amount: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<BigNumber>;
    };

    populateTransaction: {
        burn(
            amount: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<PopulatedTransaction>;

        isEnoughOn(
            account: string,
            amount: BigNumberish,
            overrides?: CallOverrides
        ): Promise<PopulatedTransaction>;

        mint(
            to: string,
            amount: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<PopulatedTransaction>;

        safeDeposit(
            from: string,
            to: string,
            amount: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<PopulatedTransaction>;

        safeWithdraw(
            from: string,
            to: string,
            amount: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<PopulatedTransaction>;

        xburn(
            from: string,
            amount: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<PopulatedTransaction>;
    };
}
