/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
    ethers,
    EventFilter,
    Signer,
    BigNumber,
    BigNumberish,
    PopulatedTransaction,
    BaseContract,
    ContractTransaction,
    Overrides,
    CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
    TypedEventFilter,
    TypedEvent,
    TypedListener,
    OnEvent,
} from "./common";

export interface ISAFEInterface extends ethers.utils.Interface {
    functions: {
        "addSafe(address[])": FunctionFragment;
        "changeSafe(address,address)": FunctionFragment;
        "isSafe(address)": FunctionFragment;
        "removeSafe(address)": FunctionFragment;
    };

    encodeFunctionData(functionFragment: "addSafe", values: [string[]]): string;
    encodeFunctionData(
        functionFragment: "changeSafe",
        values: [string, string]
    ): string;
    encodeFunctionData(functionFragment: "isSafe", values: [string]): string;
    encodeFunctionData(
        functionFragment: "removeSafe",
        values: [string]
    ): string;

    decodeFunctionResult(functionFragment: "addSafe", data: BytesLike): Result;
    decodeFunctionResult(
        functionFragment: "changeSafe",
        data: BytesLike
    ): Result;
    decodeFunctionResult(functionFragment: "isSafe", data: BytesLike): Result;
    decodeFunctionResult(
        functionFragment: "removeSafe",
        data: BytesLike
    ): Result;

    events: {};
}

export interface ISAFE extends BaseContract {
    connect(signerOrProvider: Signer | Provider | string): this;
    attach(addressOrName: string): this;
    deployed(): Promise<this>;

    interface: ISAFEInterface;

    queryFilter<TEvent extends TypedEvent>(
        event: TypedEventFilter<TEvent>,
        fromBlockOrBlockhash?: string | number | undefined,
        toBlock?: string | number | undefined
    ): Promise<Array<TEvent>>;

    listeners<TEvent extends TypedEvent>(
        eventFilter?: TypedEventFilter<TEvent>
    ): Array<TypedListener<TEvent>>;
    listeners(eventName?: string): Array<Listener>;
    removeAllListeners<TEvent extends TypedEvent>(
        eventFilter: TypedEventFilter<TEvent>
    ): this;
    removeAllListeners(eventName?: string): this;
    off: OnEvent<this>;
    on: OnEvent<this>;
    once: OnEvent<this>;
    removeListener: OnEvent<this>;

    functions: {
        addSafe(
            _safe: string[],
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<ContractTransaction>;

        changeSafe(
            _from: string,
            _to: string,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<ContractTransaction>;

        isSafe(_safe: string, overrides?: CallOverrides): Promise<[boolean]>;

        removeSafe(
            _safe: string,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<ContractTransaction>;
    };

    addSafe(
        _safe: string[],
        overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeSafe(
        _from: string,
        _to: string,
        overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isSafe(_safe: string, overrides?: CallOverrides): Promise<boolean>;

    removeSafe(
        _safe: string,
        overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    callStatic: {
        addSafe(_safe: string[], overrides?: CallOverrides): Promise<void>;

        changeSafe(
            _from: string,
            _to: string,
            overrides?: CallOverrides
        ): Promise<void>;

        isSafe(_safe: string, overrides?: CallOverrides): Promise<boolean>;

        removeSafe(_safe: string, overrides?: CallOverrides): Promise<void>;
    };

    filters: {};

    estimateGas: {
        addSafe(
            _safe: string[],
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<BigNumber>;

        changeSafe(
            _from: string,
            _to: string,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<BigNumber>;

        isSafe(_safe: string, overrides?: CallOverrides): Promise<BigNumber>;

        removeSafe(
            _safe: string,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<BigNumber>;
    };

    populateTransaction: {
        addSafe(
            _safe: string[],
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<PopulatedTransaction>;

        changeSafe(
            _from: string,
            _to: string,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<PopulatedTransaction>;

        isSafe(
            _safe: string,
            overrides?: CallOverrides
        ): Promise<PopulatedTransaction>;

        removeSafe(
            _safe: string,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<PopulatedTransaction>;
    };
}
