/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
    ethers,
    EventFilter,
    Signer,
    BigNumber,
    BigNumberish,
    PopulatedTransaction,
    BaseContract,
    ContractTransaction,
    Overrides,
    CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
    TypedEventFilter,
    TypedEvent,
    TypedListener,
    OnEvent,
} from "./common";

export interface IStrategyInterface extends ethers.utils.Interface {
    functions: {
        "getJson(string,string)": FunctionFragment;
        "sendJson(string,string)": FunctionFragment;
    };

    encodeFunctionData(
        functionFragment: "getJson",
        values: [string, string]
    ): string;
    encodeFunctionData(
        functionFragment: "sendJson",
        values: [string, string]
    ): string;

    decodeFunctionResult(functionFragment: "getJson", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "sendJson", data: BytesLike): Result;

    events: {};
}

export interface IStrategy extends BaseContract {
    connect(signerOrProvider: Signer | Provider | string): this;
    attach(addressOrName: string): this;
    deployed(): Promise<this>;

    interface: IStrategyInterface;

    queryFilter<TEvent extends TypedEvent>(
        event: TypedEventFilter<TEvent>,
        fromBlockOrBlockhash?: string | number | undefined,
        toBlock?: string | number | undefined
    ): Promise<Array<TEvent>>;

    listeners<TEvent extends TypedEvent>(
        eventFilter?: TypedEventFilter<TEvent>
    ): Array<TypedListener<TEvent>>;
    listeners(eventName?: string): Array<Listener>;
    removeAllListeners<TEvent extends TypedEvent>(
        eventFilter: TypedEventFilter<TEvent>
    ): this;
    removeAllListeners(eventName?: string): this;
    off: OnEvent<this>;
    on: OnEvent<this>;
    once: OnEvent<this>;
    removeListener: OnEvent<this>;

    functions: {
        getJson(
            _function: string,
            _values: string,
            overrides?: CallOverrides
        ): Promise<[string]>;

        sendJson(
            _function: string,
            _values: string,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<ContractTransaction>;
    };

    getJson(
        _function: string,
        _values: string,
        overrides?: CallOverrides
    ): Promise<string>;

    sendJson(
        _function: string,
        _values: string,
        overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    callStatic: {
        getJson(
            _function: string,
            _values: string,
            overrides?: CallOverrides
        ): Promise<string>;

        sendJson(
            _function: string,
            _values: string,
            overrides?: CallOverrides
        ): Promise<void>;
    };

    filters: {};

    estimateGas: {
        getJson(
            _function: string,
            _values: string,
            overrides?: CallOverrides
        ): Promise<BigNumber>;

        sendJson(
            _function: string,
            _values: string,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<BigNumber>;
    };

    populateTransaction: {
        getJson(
            _function: string,
            _values: string,
            overrides?: CallOverrides
        ): Promise<PopulatedTransaction>;

        sendJson(
            _function: string,
            _values: string,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<PopulatedTransaction>;
    };
}
