/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
    ethers,
    EventFilter,
    Signer,
    BigNumber,
    BigNumberish,
    PopulatedTransaction,
    BaseContract,
    ContractTransaction,
    Overrides,
    CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
    TypedEventFilter,
    TypedEvent,
    TypedListener,
    OnEvent,
} from "./common";

export interface PageNFTBankInterface extends ethers.utils.Interface {
    functions: {
        "Buy(uint256)": FunctionFragment;
        "Sell(uint256)": FunctionFragment;
        "getPrice()": FunctionFragment;
        "pageMinter()": FunctionFragment;
        "pageNFT()": FunctionFragment;
        "pageToken()": FunctionFragment;
        "setBuyPrice(uint256)": FunctionFragment;
        "setSellPrice(uint256)": FunctionFragment;
    };

    encodeFunctionData(functionFragment: "Buy", values: [BigNumberish]): string;
    encodeFunctionData(
        functionFragment: "Sell",
        values: [BigNumberish]
    ): string;
    encodeFunctionData(
        functionFragment: "getPrice",
        values?: undefined
    ): string;
    encodeFunctionData(
        functionFragment: "pageMinter",
        values?: undefined
    ): string;
    encodeFunctionData(functionFragment: "pageNFT", values?: undefined): string;
    encodeFunctionData(
        functionFragment: "pageToken",
        values?: undefined
    ): string;
    encodeFunctionData(
        functionFragment: "setBuyPrice",
        values: [BigNumberish]
    ): string;
    encodeFunctionData(
        functionFragment: "setSellPrice",
        values: [BigNumberish]
    ): string;

    decodeFunctionResult(functionFragment: "Buy", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "Sell", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
    decodeFunctionResult(
        functionFragment: "pageMinter",
        data: BytesLike
    ): Result;
    decodeFunctionResult(functionFragment: "pageNFT", data: BytesLike): Result;
    decodeFunctionResult(
        functionFragment: "pageToken",
        data: BytesLike
    ): Result;
    decodeFunctionResult(
        functionFragment: "setBuyPrice",
        data: BytesLike
    ): Result;
    decodeFunctionResult(
        functionFragment: "setSellPrice",
        data: BytesLike
    ): Result;

    events: {};
}

export interface PageNFTBank extends BaseContract {
    connect(signerOrProvider: Signer | Provider | string): this;
    attach(addressOrName: string): this;
    deployed(): Promise<this>;

    interface: PageNFTBankInterface;

    queryFilter<TEvent extends TypedEvent>(
        event: TypedEventFilter<TEvent>,
        fromBlockOrBlockhash?: string | number | undefined,
        toBlock?: string | number | undefined
    ): Promise<Array<TEvent>>;

    listeners<TEvent extends TypedEvent>(
        eventFilter?: TypedEventFilter<TEvent>
    ): Array<TypedListener<TEvent>>;
    listeners(eventName?: string): Array<Listener>;
    removeAllListeners<TEvent extends TypedEvent>(
        eventFilter: TypedEventFilter<TEvent>
    ): this;
    removeAllListeners(eventName?: string): this;
    off: OnEvent<this>;
    on: OnEvent<this>;
    once: OnEvent<this>;
    removeListener: OnEvent<this>;

    functions: {
        Buy(
            tokenId: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<ContractTransaction>;

        Sell(
            tokenId: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<ContractTransaction>;

        getPrice(
            overrides?: CallOverrides
        ): Promise<
            [BigNumber, BigNumber] & { sell: BigNumber; buy: BigNumber }
        >;

        pageMinter(overrides?: CallOverrides): Promise<[string]>;

        pageNFT(overrides?: CallOverrides): Promise<[string]>;

        pageToken(overrides?: CallOverrides): Promise<[string]>;

        setBuyPrice(
            _price: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<ContractTransaction>;

        setSellPrice(
            _price: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<ContractTransaction>;
    };

    Buy(
        tokenId: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    Sell(
        tokenId: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getPrice(
        overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { sell: BigNumber; buy: BigNumber }>;

    pageMinter(overrides?: CallOverrides): Promise<string>;

    pageNFT(overrides?: CallOverrides): Promise<string>;

    pageToken(overrides?: CallOverrides): Promise<string>;

    setBuyPrice(
        _price: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setSellPrice(
        _price: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    callStatic: {
        Buy(tokenId: BigNumberish, overrides?: CallOverrides): Promise<void>;

        Sell(tokenId: BigNumberish, overrides?: CallOverrides): Promise<void>;

        getPrice(
            overrides?: CallOverrides
        ): Promise<
            [BigNumber, BigNumber] & { sell: BigNumber; buy: BigNumber }
        >;

        pageMinter(overrides?: CallOverrides): Promise<string>;

        pageNFT(overrides?: CallOverrides): Promise<string>;

        pageToken(overrides?: CallOverrides): Promise<string>;

        setBuyPrice(
            _price: BigNumberish,
            overrides?: CallOverrides
        ): Promise<void>;

        setSellPrice(
            _price: BigNumberish,
            overrides?: CallOverrides
        ): Promise<void>;
    };

    filters: {};

    estimateGas: {
        Buy(
            tokenId: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<BigNumber>;

        Sell(
            tokenId: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<BigNumber>;

        getPrice(overrides?: CallOverrides): Promise<BigNumber>;

        pageMinter(overrides?: CallOverrides): Promise<BigNumber>;

        pageNFT(overrides?: CallOverrides): Promise<BigNumber>;

        pageToken(overrides?: CallOverrides): Promise<BigNumber>;

        setBuyPrice(
            _price: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<BigNumber>;

        setSellPrice(
            _price: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<BigNumber>;
    };

    populateTransaction: {
        Buy(
            tokenId: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<PopulatedTransaction>;

        Sell(
            tokenId: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<PopulatedTransaction>;

        getPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

        pageMinter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

        pageNFT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

        pageToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

        setBuyPrice(
            _price: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<PopulatedTransaction>;

        setSellPrice(
            _price: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<PopulatedTransaction>;
    };
}
