/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
    ethers,
    EventFilter,
    Signer,
    BigNumber,
    BigNumberish,
    PopulatedTransaction,
    BaseContract,
    ContractTransaction,
    CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
    TypedEventFilter,
    TypedEvent,
    TypedListener,
    OnEvent,
} from "./common";

export interface PageNFTMarketInterface extends ethers.utils.Interface {
    functions: {
        "pageMinter()": FunctionFragment;
        "pageNFT()": FunctionFragment;
        "pageToken()": FunctionFragment;
    };

    encodeFunctionData(
        functionFragment: "pageMinter",
        values?: undefined
    ): string;
    encodeFunctionData(functionFragment: "pageNFT", values?: undefined): string;
    encodeFunctionData(
        functionFragment: "pageToken",
        values?: undefined
    ): string;

    decodeFunctionResult(
        functionFragment: "pageMinter",
        data: BytesLike
    ): Result;
    decodeFunctionResult(functionFragment: "pageNFT", data: BytesLike): Result;
    decodeFunctionResult(
        functionFragment: "pageToken",
        data: BytesLike
    ): Result;

    events: {};
}

export interface PageNFTMarket extends BaseContract {
    connect(signerOrProvider: Signer | Provider | string): this;
    attach(addressOrName: string): this;
    deployed(): Promise<this>;

    interface: PageNFTMarketInterface;

    queryFilter<TEvent extends TypedEvent>(
        event: TypedEventFilter<TEvent>,
        fromBlockOrBlockhash?: string | number | undefined,
        toBlock?: string | number | undefined
    ): Promise<Array<TEvent>>;

    listeners<TEvent extends TypedEvent>(
        eventFilter?: TypedEventFilter<TEvent>
    ): Array<TypedListener<TEvent>>;
    listeners(eventName?: string): Array<Listener>;
    removeAllListeners<TEvent extends TypedEvent>(
        eventFilter: TypedEventFilter<TEvent>
    ): this;
    removeAllListeners(eventName?: string): this;
    off: OnEvent<this>;
    on: OnEvent<this>;
    once: OnEvent<this>;
    removeListener: OnEvent<this>;

    functions: {
        pageMinter(overrides?: CallOverrides): Promise<[string]>;

        pageNFT(overrides?: CallOverrides): Promise<[string]>;

        pageToken(overrides?: CallOverrides): Promise<[string]>;
    };

    pageMinter(overrides?: CallOverrides): Promise<string>;

    pageNFT(overrides?: CallOverrides): Promise<string>;

    pageToken(overrides?: CallOverrides): Promise<string>;

    callStatic: {
        pageMinter(overrides?: CallOverrides): Promise<string>;

        pageNFT(overrides?: CallOverrides): Promise<string>;

        pageToken(overrides?: CallOverrides): Promise<string>;
    };

    filters: {};

    estimateGas: {
        pageMinter(overrides?: CallOverrides): Promise<BigNumber>;

        pageNFT(overrides?: CallOverrides): Promise<BigNumber>;

        pageToken(overrides?: CallOverrides): Promise<BigNumber>;
    };

    populateTransaction: {
        pageMinter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

        pageNFT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

        pageToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;
    };
}
