/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
    ethers,
    EventFilter,
    Signer,
    BigNumber,
    BigNumberish,
    PopulatedTransaction,
    BaseContract,
    ContractTransaction,
    Overrides,
    CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
    TypedEventFilter,
    TypedEvent,
    TypedListener,
    OnEvent,
} from "./common";

export interface PageProfileInterface extends ethers.utils.Interface {
    functions: {
        "PAGE_MINTER()": FunctionFragment;
        "SocialById(uint256)": FunctionFragment;
        "StatusById(uint256)": FunctionFragment;
        "_add_social(string,string)": FunctionFragment;
        "_add_status(string)": FunctionFragment;
    };

    encodeFunctionData(
        functionFragment: "PAGE_MINTER",
        values?: undefined
    ): string;
    encodeFunctionData(
        functionFragment: "SocialById",
        values: [BigNumberish]
    ): string;
    encodeFunctionData(
        functionFragment: "StatusById",
        values: [BigNumberish]
    ): string;
    encodeFunctionData(
        functionFragment: "_add_social",
        values: [string, string]
    ): string;
    encodeFunctionData(
        functionFragment: "_add_status",
        values: [string]
    ): string;

    decodeFunctionResult(
        functionFragment: "PAGE_MINTER",
        data: BytesLike
    ): Result;
    decodeFunctionResult(
        functionFragment: "SocialById",
        data: BytesLike
    ): Result;
    decodeFunctionResult(
        functionFragment: "StatusById",
        data: BytesLike
    ): Result;
    decodeFunctionResult(
        functionFragment: "_add_social",
        data: BytesLike
    ): Result;
    decodeFunctionResult(
        functionFragment: "_add_status",
        data: BytesLike
    ): Result;

    events: {};
}

export interface PageProfile extends BaseContract {
    connect(signerOrProvider: Signer | Provider | string): this;
    attach(addressOrName: string): this;
    deployed(): Promise<this>;

    interface: PageProfileInterface;

    queryFilter<TEvent extends TypedEvent>(
        event: TypedEventFilter<TEvent>,
        fromBlockOrBlockhash?: string | number | undefined,
        toBlock?: string | number | undefined
    ): Promise<Array<TEvent>>;

    listeners<TEvent extends TypedEvent>(
        eventFilter?: TypedEventFilter<TEvent>
    ): Array<TypedListener<TEvent>>;
    listeners(eventName?: string): Array<Listener>;
    removeAllListeners<TEvent extends TypedEvent>(
        eventFilter: TypedEventFilter<TEvent>
    ): this;
    removeAllListeners(eventName?: string): this;
    off: OnEvent<this>;
    on: OnEvent<this>;
    once: OnEvent<this>;
    removeListener: OnEvent<this>;

    functions: {
        PAGE_MINTER(overrides?: CallOverrides): Promise<[string]>;

        SocialById(
            arg0: BigNumberish,
            overrides?: CallOverrides
        ): Promise<
            [BigNumber, string, string, string] & {
                uid: BigNumber;
                author: string;
                title: string;
                url: string;
            }
        >;

        StatusById(
            arg0: BigNumberish,
            overrides?: CallOverrides
        ): Promise<
            [BigNumber, string, string] & {
                uid: BigNumber;
                author: string;
                text: string;
            }
        >;

        _add_social(
            title: string,
            url: string,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<ContractTransaction>;

        _add_status(
            text: string,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<ContractTransaction>;
    };

    PAGE_MINTER(overrides?: CallOverrides): Promise<string>;

    SocialById(
        arg0: BigNumberish,
        overrides?: CallOverrides
    ): Promise<
        [BigNumber, string, string, string] & {
            uid: BigNumber;
            author: string;
            title: string;
            url: string;
        }
    >;

    StatusById(
        arg0: BigNumberish,
        overrides?: CallOverrides
    ): Promise<
        [BigNumber, string, string] & {
            uid: BigNumber;
            author: string;
            text: string;
        }
    >;

    _add_social(
        title: string,
        url: string,
        overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _add_status(
        text: string,
        overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    callStatic: {
        PAGE_MINTER(overrides?: CallOverrides): Promise<string>;

        SocialById(
            arg0: BigNumberish,
            overrides?: CallOverrides
        ): Promise<
            [BigNumber, string, string, string] & {
                uid: BigNumber;
                author: string;
                title: string;
                url: string;
            }
        >;

        StatusById(
            arg0: BigNumberish,
            overrides?: CallOverrides
        ): Promise<
            [BigNumber, string, string] & {
                uid: BigNumber;
                author: string;
                text: string;
            }
        >;

        _add_social(
            title: string,
            url: string,
            overrides?: CallOverrides
        ): Promise<void>;

        _add_status(text: string, overrides?: CallOverrides): Promise<void>;
    };

    filters: {};

    estimateGas: {
        PAGE_MINTER(overrides?: CallOverrides): Promise<BigNumber>;

        SocialById(
            arg0: BigNumberish,
            overrides?: CallOverrides
        ): Promise<BigNumber>;

        StatusById(
            arg0: BigNumberish,
            overrides?: CallOverrides
        ): Promise<BigNumber>;

        _add_social(
            title: string,
            url: string,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<BigNumber>;

        _add_status(
            text: string,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<BigNumber>;
    };

    populateTransaction: {
        PAGE_MINTER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

        SocialById(
            arg0: BigNumberish,
            overrides?: CallOverrides
        ): Promise<PopulatedTransaction>;

        StatusById(
            arg0: BigNumberish,
            overrides?: CallOverrides
        ): Promise<PopulatedTransaction>;

        _add_social(
            title: string,
            url: string,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<PopulatedTransaction>;

        _add_status(
            text: string,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<PopulatedTransaction>;
    };
}
