/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
    ethers,
    EventFilter,
    Signer,
    BigNumber,
    BigNumberish,
    PopulatedTransaction,
    BaseContract,
    ContractTransaction,
    Overrides,
    CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
    TypedEventFilter,
    TypedEvent,
    TypedListener,
    OnEvent,
} from "./common";

export interface PageNFTBankInterface extends ethers.utils.Interface {
    functions: {
        "Buy(uint256)": FunctionFragment;
        "PAGE_MINTER()": FunctionFragment;
        "PAGE_NFT()": FunctionFragment;
        "PAGE_TOKEN()": FunctionFragment;
        "Sell(uint256)": FunctionFragment;
        "getPrice()": FunctionFragment;
        "setBuyPrice(uint256)": FunctionFragment;
        "setSellPrice(uint256)": FunctionFragment;
    };

    encodeFunctionData(functionFragment: "Buy", values: [BigNumberish]): string;
    encodeFunctionData(
        functionFragment: "PAGE_MINTER",
        values?: undefined
    ): string;
    encodeFunctionData(
        functionFragment: "PAGE_NFT",
        values?: undefined
    ): string;
    encodeFunctionData(
        functionFragment: "PAGE_TOKEN",
        values?: undefined
    ): string;
    encodeFunctionData(
        functionFragment: "Sell",
        values: [BigNumberish]
    ): string;
    encodeFunctionData(
        functionFragment: "getPrice",
        values?: undefined
    ): string;
    encodeFunctionData(
        functionFragment: "setBuyPrice",
        values: [BigNumberish]
    ): string;
    encodeFunctionData(
        functionFragment: "setSellPrice",
        values: [BigNumberish]
    ): string;

    decodeFunctionResult(functionFragment: "Buy", data: BytesLike): Result;
    decodeFunctionResult(
        functionFragment: "PAGE_MINTER",
        data: BytesLike
    ): Result;
    decodeFunctionResult(functionFragment: "PAGE_NFT", data: BytesLike): Result;
    decodeFunctionResult(
        functionFragment: "PAGE_TOKEN",
        data: BytesLike
    ): Result;
    decodeFunctionResult(functionFragment: "Sell", data: BytesLike): Result;
    decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
    decodeFunctionResult(
        functionFragment: "setBuyPrice",
        data: BytesLike
    ): Result;
    decodeFunctionResult(
        functionFragment: "setSellPrice",
        data: BytesLike
    ): Result;

    events: {};
}

export interface PageNFTBank extends BaseContract {
    connect(signerOrProvider: Signer | Provider | string): this;
    attach(addressOrName: string): this;
    deployed(): Promise<this>;

    interface: PageNFTBankInterface;

    queryFilter<TEvent extends TypedEvent>(
        event: TypedEventFilter<TEvent>,
        fromBlockOrBlockhash?: string | number | undefined,
        toBlock?: string | number | undefined
    ): Promise<Array<TEvent>>;

    listeners<TEvent extends TypedEvent>(
        eventFilter?: TypedEventFilter<TEvent>
    ): Array<TypedListener<TEvent>>;
    listeners(eventName?: string): Array<Listener>;
    removeAllListeners<TEvent extends TypedEvent>(
        eventFilter: TypedEventFilter<TEvent>
    ): this;
    removeAllListeners(eventName?: string): this;
    off: OnEvent<this>;
    on: OnEvent<this>;
    once: OnEvent<this>;
    removeListener: OnEvent<this>;

    functions: {
        Buy(
            tokenId: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<ContractTransaction>;

        PAGE_MINTER(overrides?: CallOverrides): Promise<[string]>;

        PAGE_NFT(overrides?: CallOverrides): Promise<[string]>;

        PAGE_TOKEN(overrides?: CallOverrides): Promise<[string]>;

        Sell(
            tokenId: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<ContractTransaction>;

        getPrice(
            overrides?: CallOverrides
        ): Promise<
            [BigNumber, BigNumber] & { sell: BigNumber; buy: BigNumber }
        >;

        setBuyPrice(
            _price: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<ContractTransaction>;

        setSellPrice(
            _price: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<ContractTransaction>;
    };

    Buy(
        tokenId: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    PAGE_MINTER(overrides?: CallOverrides): Promise<string>;

    PAGE_NFT(overrides?: CallOverrides): Promise<string>;

    PAGE_TOKEN(overrides?: CallOverrides): Promise<string>;

    Sell(
        tokenId: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getPrice(
        overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { sell: BigNumber; buy: BigNumber }>;

    setBuyPrice(
        _price: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setSellPrice(
        _price: BigNumberish,
        overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    callStatic: {
        Buy(tokenId: BigNumberish, overrides?: CallOverrides): Promise<void>;

        PAGE_MINTER(overrides?: CallOverrides): Promise<string>;

        PAGE_NFT(overrides?: CallOverrides): Promise<string>;

        PAGE_TOKEN(overrides?: CallOverrides): Promise<string>;

        Sell(tokenId: BigNumberish, overrides?: CallOverrides): Promise<void>;

        getPrice(
            overrides?: CallOverrides
        ): Promise<
            [BigNumber, BigNumber] & { sell: BigNumber; buy: BigNumber }
        >;

        setBuyPrice(
            _price: BigNumberish,
            overrides?: CallOverrides
        ): Promise<void>;

        setSellPrice(
            _price: BigNumberish,
            overrides?: CallOverrides
        ): Promise<void>;
    };

    filters: {};

    estimateGas: {
        Buy(
            tokenId: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<BigNumber>;

        PAGE_MINTER(overrides?: CallOverrides): Promise<BigNumber>;

        PAGE_NFT(overrides?: CallOverrides): Promise<BigNumber>;

        PAGE_TOKEN(overrides?: CallOverrides): Promise<BigNumber>;

        Sell(
            tokenId: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<BigNumber>;

        getPrice(overrides?: CallOverrides): Promise<BigNumber>;

        setBuyPrice(
            _price: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<BigNumber>;

        setSellPrice(
            _price: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<BigNumber>;
    };

    populateTransaction: {
        Buy(
            tokenId: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<PopulatedTransaction>;

        PAGE_MINTER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

        PAGE_NFT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

        PAGE_TOKEN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

        Sell(
            tokenId: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<PopulatedTransaction>;

        getPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

        setBuyPrice(
            _price: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<PopulatedTransaction>;

        setSellPrice(
            _price: BigNumberish,
            overrides?: Overrides & { from?: string | Promise<string> }
        ): Promise<PopulatedTransaction>;
    };
}
